### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain_google_genai'

### ISSUE THREAD

**Issue by prabhatpathania** [SAP-samples/btp-generative-ai-hub-use-cases#12]
While running application which were working perfectly fine suddenly I am getting the error:

> `from langchain_google_genai import ChatGoogleGenerativeAI as ChatGoogleGenerativeAI_
ModuleNotFoundError: No module named 'langchain_google_genai'`

It points to statement:

`from gen_ai_hub.proxy.langchain.init_models import init_llm
`
To reproduce, you can create a python file with just the above line of code.

**Comment by YatseaLi** [comment]
Hi @prabhatpathania,

It is due to some recent update on the [SAP Generative AI SDK package](https://pypi.org/project/generative-ai-hub-sdk/).

Please update to the latest SAP Generative AI SDK with this command:
`pip install -U generative-ai-hub-sdk[langchain]`

Kind Regards,
Yatsea

**Comment by YatseaLi** [comment]
fixed with [update to latest sdk generative-ai-hub-sdk[langchain]](https://github.com/SAP-samples/btp-generative-ai-hub-use-cases/commit/8eb2ce3e7994b4419ca98d8fc2c19690c2808eb0)
